function [M,C,N,Y] = AcroBOTDynamics(in1,in2,in3,in4)
%AcroBOTDynamics
%    [M,C,N,Y] = AcroBOTDynamics(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Feb-2023 21:30:42

c1 = in4(7,:);
c2 = in4(8,:);
c3 = in4(9,:);
l1 = in4(4,:);
l2 = in4(5,:);
l3 = in4(6,:);
m_l1 = in4(1,:);
m_l2 = in4(2,:);
m_l3 = in4(3,:);
tau_1 = in3(1,:);
tau_2 = in3(2,:);
tau_3 = in3(3,:);
theta_1 = in1(1,:);
theta_2 = in1(2,:);
theta_3 = in1(3,:);
theta_dot_1 = in2(1,:);
theta_dot_2 = in2(2,:);
theta_dot_3 = in2(3,:);
t2 = cos(theta_1);
t3 = cos(theta_2);
t4 = cos(theta_3);
t5 = sin(theta_2);
t6 = sin(theta_3);
t7 = theta_1+theta_2;
t8 = theta_2+theta_3;
t9 = c2.^2;
t10 = c3.^2;
t11 = l1.^2;
t12 = l2.^2;
t13 = l3.^2;
t14 = l1.*t2;
t15 = cos(t7);
t16 = cos(t8);
t17 = sin(t8);
t18 = t7+theta_3;
t20 = m_l2.*t9;
t21 = m_l3.*t10;
t22 = m_l3.*t12;
t23 = t10.*1.2e+1;
t24 = c2.*l1.*m_l2.*t3;
t26 = l1.*l2.*m_l3.*t3;
t27 = c3.*l2.*t4.*1.2e+1;
t28 = c3.*l2.*m_l3.*t4.*2.0;
t29 = c2.*l1.*m_l2.*t5.*2.0;
t30 = c3.*l2.*m_l3.*t6.*2.0;
t31 = l1.*l2.*m_l3.*t5.*2.0;
t33 = c3.*l2.*m_l3.*t6.*theta_dot_1;
t34 = c3.*l2.*m_l3.*t6.*theta_dot_2;
t35 = c3.*l2.*m_l3.*t6.*theta_dot_3;
t38 = (m_l2.*t12)./1.2e+1;
t39 = (m_l3.*t13)./1.2e+1;
t19 = cos(t18);
t25 = l2.*t15;
t36 = c3.*l1.*m_l3.*t16;
t37 = c3.*l1.*m_l3.*t17.*2.0;
t40 = c3.*l1.*t16.*1.2e+1;
t41 = -t35;
t43 = t13+t23+t27;
t32 = c3.*t19;
t42 = t30+t37;
t47 = (m_l3.*t43)./1.2e+1;
t48 = t29+t31+t37;
t49 = t40+t43;
t54 = t20+t21+t22+t24+t26+t28+t36+t38+t39;
t44 = (t42.*theta_dot_1)./2.0;
t45 = (t42.*theta_dot_3)./2.0;
t50 = (t48.*theta_dot_1)./2.0;
t51 = (t48.*theta_dot_2)./2.0;
t53 = (m_l3.*t49)./1.2e+1;
M = reshape([t24+t26+t36+t54+(m_l1.*t11)./1.2e+1+m_l2.*t11+m_l3.*t11+c1.^2.*m_l1,t54,t53,t54,t20+t21+t22+t28+t38+t39,t47,t53,t47,(m_l3.*(t13+t23))./1.2e+1],[3,3]);
if nargout > 1
    t46 = -t45;
    t52 = -t51;
    C = reshape([t46+t52,t41+t50,t34+t44,t46-t50+t52,t41,t33+t34,-t44-(t42.*theta_dot_2)./2.0-(m_l3.*theta_dot_3.*(c3.*l2.*t6.*1.2e+1+c3.*l1.*t17.*1.2e+1))./1.2e+1,-t33-t34+t41,0.0],[3,3]);
end
if nargout > 2
    N = [m_l3.*(t14+t25+t32).*(9.81e+2./1.0e+2)+m_l2.*(t14+c2.*t15).*(9.81e+2./1.0e+2)+c1.*m_l1.*t2.*(9.81e+2./1.0e+2);m_l3.*(t25+t32).*(9.81e+2./1.0e+2)+c2.*m_l2.*t15.*(9.81e+2./1.0e+2);m_l3.*t32.*(9.81e+2./1.0e+2)];
end
if nargout > 3
    Y = [tau_1;tau_2;tau_3];
end
