function animateAcroBOT(x, dt, SYS)
% x: collection of state vectors at each time, similar to output from ode45
% dt: (difference in time between each row of xout, generated by calling
% ode45 with the argument [tstart:dt:tfinal];)
close all;
set(0, 'DefaultAxesFontSize', 24);
set(0, 'DefaultLineMarkerSize', 10);
set(0,'defaultfigurecolor',[1 1 1]);
set(0,'DefaultAxesXGrid','off','DefaultAxesYGrid','off')
set(groot,'defaulttextinterpreter','latex');
set(groot, 'defaultAxesTickLabelInterpreter','latex');
set(groot, 'defaultLegendInterpreter','latex');

bRecord = 0;  % Uncomment this to save a video
if bRecord
    % Define video recording parameters
    Filename = 'current_animation';
    v = VideoWriter(Filename, 'MPEG-4');
    myVideo.Quality = 100;
    open(v);
end

% Define parameters
m = SYS.m;
l = SYS.l;
c = SYS.c;

% Define axis window
windowSize = sum(SYS.l) + 0.5;
xmin = -windowSize;
xmax = windowSize;
ymin = -windowSize;
ymax = windowSize;

Fig = figure('Color', 'w');

% Create trace of trajectory and particle object
h = animatedline('LineStyle', ':', 'LineWidth', 1.5);
manipulator = [];
endeffector = [];
joints = [];

% Set up axes
axis equal
axis([xmin xmax ymin ymax])
xlabel('x')
ylabel('y')

% draw
base = [0;0];
L = 1;
for ii = 1:length(x)
    a = tic;
    
    set(gcf,'DoubleBuffer','on');
    
    q1 = x(ii,1);
    q2 = x(ii,2);
    q3 = x(ii,3);
    joint1 = [l(1)*cos(q1);l(1)*sin(q1)];
    joint2 = [l(1)*cos(q1) + l(2)*cos(q1+q2);l(1)*sin(q1) + l(2)*sin(q1+q2)]; 
    joint3 = [l(1)*cos(q1) + l(2)*cos(q1+q2) + l(3)*cos(q1+q2+q3);l(1)*sin(q1) + l(2)*sin(q1+q2) + l(3)*sin(q1+q2+q3)];
    delete(manipulator);
    delete(endeffector);
    delete(joints);
    manipulator = line([base(1), joint1(1), joint2(1), joint3(1)], [base(2), joint1(2), joint2(2), joint3(2)], 'Color', [0;0;0],'LineStyle','-');
    joints = line([joint1(1), joint2(1)], [joint1(2), joint2(2)],'Marker','.', 'MarkerSize', 20);
    endeffector = line(joint3(1), joint3(2), 'Color', [1;0;0],'Marker','.', 'MarkerSize', 20);
    addpoints(h,joint3(1), joint3(2));
    
    drawnow limitrate
    
    if bRecord
        frame = getframe(gcf);
        writeVideo(v,frame);
    else
        pause(dt - toc(a)); % waits if drawing frame took less time than anticipated
    end
end

if bRecord
    close(v);
end