function dA = computedA(in1,in2)
%computedA
%    dA = computedA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Dec-2022 09:00:12

dA = reshape([0.0,0.0,0.0,0.0],[2,2]);
