function A = computeA(in1)
%computeA
%    A = computeA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Dec-2022 09:00:11

A = reshape([-1.0,1.0,2.0,2.0],[2,2]);
